travis:
  secure:
    BINSTAR_TOKEN: Io3zljXmRY0BKiZ3H2CeIpaJv5I/HXtz3davWVHQwwz0JwvPJzxrsAzAkN/t488xam+vlQEYB/4AvTdn1TkjzKV2V/67TMQLIwAmRTxii89UtX1iJo/5AwNTRBL7IByVdi8/6k1u294+Hh7dWe7WITYuzJPmTMXtO5P30R1z4nzANndbIiR8dVcW7VUTqFvLP+N71pHGDb4WneQ+yU0gScyhn83PL2gKlCHjUq83b3nzJPDZB75jMY3mRFP66uH3kAxgCq9XzJIEVY5kpX525vir08ySxoUh3sIphJ1KqAQN8bM1Jo6qRB5uBSZu8fiAt6UrNgseLM4SWuPcIQg3QUahPtiqU2FiDL95E8vu6xcVhmPh1x3vusjfaEVMCVGWnHxJDZEGEqW7RvzTOM5runYSPj9YKfjt8cAZavPmwyEGwYr9oobQM8PqCVGSP/CUE1OZ1DctGhCnuko6jLCb76uexhlkadw0dO2hhtLhKPkP/9mfKZSgQRu4agKEqcwKYMTdE0IbefsYPlspVU+bFQqVY9wFoD88NRDdeOP3mT4zBxWQ3O73b0nYW/r77E1uOwPLvKLQQG39QyFv6KVvlpkaBLFKq5B0PVtWDUaZHhcbz7FcjB8hTcXWujgvkFeLhFGOa04CK3QIuW/9lpdn4R8K3xEfD9mX2JBL8io6+9U=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
